version: '3.3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    hostname: zookeeper
    volumes:
      - /home/azureuser/zookeeper/data:/opt/zookeeper-3.4.13/data

  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1,event_log:1:1"
      KAFKA_ADVERTISED_HOST_NAME: "kafka-acit3855-lab6.eastus.cloudapp.azure.com"
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://kafka-acit3855-lab6.eastus.cloudapp.azure.com:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/azureuser/kafka:/kafka/kafka-logs
    depends_on:
      - "zookeeper"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'events'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'Vincent'
      MYSQL_PASSWORD: 'Ymca9622$'
    ports:
      - '3306:3306'
    expose:
      - '3306'  
    volumes:
      - my-db:/var/lib/mysql
  
  receiver:
    image: receiver:latest
    ports:
      - "8080"
    networks:
      - "api.network"
    environment:
      - TARGET_ENV=test
    volumes:
      - /home/azureuser/config/receiver:/config
      - /home/azureuser/logs:/logs
    depends_on:
      - "kafka"

  storage:
    image: storage:latest
    ports:
      - "8090"
    networks:
      - "api.network"
    environment:
      - TARGET_ENV=test
    volumes:
      - /home/azureuser/config/storage:/config
      - /home/azureuser/logs:/logs
    depends_on:
      - "kafka"
      - "db"

  processing:
    image: processing:latest
    ports:
      - "8100"
    networks:
      - "api.network"
    environment:
      - TARGET_ENV=test
    volumes:
      - /home/azureuser/config/processing:/config
      - /home/azureuser/logs:/logs
      - processing-db:/data
    depends_on:
      - "storage"
      
  audit:
    image: audit:latest
    ports:
      - "8110"
    networks:
      - "api.network"
    environment:
      - TARGET_ENV=test
    volumes:
      - /home/azureuser/config/audit_log:/config
      - /home/azureuser/logs:/logs
    depends_on:
      - "kafka"
      - "db"

  dashboard-ui:
    image: dashboard-ui:latest
    ports:
      - "3000"
    networks:
      - "api.network"
    depends_on:
      - "processing"
      - "audit"

  event-logger:
    image: event-logger:latest
    ports:
      - "8120"
    networks:
      - "api.network"
    environment:
      - TARGET_ENV=test
    volumes:
      - /home/azureuser/config/event_logger:/config
      - /home/azureuser/logs:/logs
      - event-log-db:/data
    depends_on:
      - "receiver"
      - "storage"
      - "processing"

  anomaly-detector:
    image: anomaly-detector:latest
    ports:
      - "8130"
    networks:
      - "api.network"
    environment:
      - TARGET_ENV=test
    volumes:
      - /home/azureuser/config/anomaly_detector:/config
      - /home/azureuser/logs:/logs
    depends_on:
      - "receiver"
      - "storage"

  nginx:
    image: nginx:latest
    volumes:
      - /home/azureuser/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "receiver"
      - "storage"
      - "processing"
      - "audit"
      - "dashboard-ui"
    ports:
      - "80:80"
    networks:
      - "api.network"
volumes:
  my-db:
  processing-db:
  event-log-db:

networks:
  api.network: